version: '3.7'

services:
  rune-testnet:
    container_name: rune-testnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    env_file: .env
    restart: always
